spring:
  application:
    name: mdd-api
  config:
    import:
      - optional:file:.env[.properties]
      - classpath:authentication.yml
  datasource:
    hikari:
      connection-timeout: 5000
      validation-timeout: 2000
      data-source-properties:
        connectTimeout: 5000
        socketTimeout: 30000

server:
  port: 9001

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-components: always
      show-details: never

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html

mdd:
  authentication:
    jwt:
      secret: ${MDD_JWT_SECRET}
      expiration: ${MDD_JWT_EXPIRATION:PT8H}
      secure-cookie: ${MDD_JWT_SECURE_COOKIE:true}
