sonar.organization=manooweb
sonar.projectKey=manooweb_projet5-mdd-front
sonar.projectName=MDD frontend
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts
sonar.exclusions=src/testing/**
sonar.javascript.lcov.reportPaths=../docs/reports/coverage/front-vitest/lcov.info,../docs/reports/coverage/front-e2e/lcov.info
