package com.openclassrooms.mddapi.system.error;

public enum ApiErrorCode {
  DUPLICATE_IDENTITY,
  INVALID_CREDENTIALS,
  INVALID_REQUEST,
  RESOURCE_NOT_FOUND,
  AUTHENTICATION_REQUIRED,
  ACCESS_DENIED,
  UNEXPECTED_ERROR
}
